### PR TITLE
Make generated file name to assign default value from module or class

### PR DESCRIPTION
**Pull request by mstefaniuk**
In previous versions filename property was not required so I would like to keep this behaviour.

### CODE REVIEW

**Comment by wcandillon** [comment]
@mstefaniuk  Thank you!

**Comment by mstefaniuk** [comment]
I've noticed that you changed version from 0.2.19 to 0.2.2 but this not fits semantic vesioning scheme. I'm waiting for this version use it.

**Comment by wcandillon** [comment]
@mstefaniuk I released 0.3.0. Does it work for you?

**Comment by mstefaniuk** [comment]
@wcandillon My patch is not adding .js extensions to file names. Please check new (this time tested) pull request wcandillon/grunt-swagger-js-codegen#21 with resolved this issue.

**Pull request merged**
